<#
.SYNOPSIS
    Open the Markdown Editor, optionally on a file.

.DESCRIPTION
    Launch copies go under %TEMP%, never into this folder.
    Edit this script. Do not edit markdown-editor.html (generated by build.js).

.PARAMETER Path
    A .md / .markdown / .txt file to open. Omit for a blank editor.

.PARAMETER Install
    Add "Open with Markdown Editor" to the Explorer menu for .md files.
    Does not change the default double-click app.

.PARAMETER Uninstall
    Remove that menu entry.

.PARAMETER NoLaunch
    Write the injected HTML under %TEMP% and print its path. Do not open a browser.
#>
[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [string]$Path,
    [switch]$Install,
    [switch]$Uninstall,
    [switch]$NoLaunch
)

$ErrorActionPreference = "Stop"
$Root = $PSScriptRoot
$HtmlFile = Join-Path $Root "markdown-editor.html"
$RegKey = "HKCU:\Software\Classes\SystemFileAssociations\.md\shell\MarkdownEditor"

function Fail([string]$Message) {
    Write-Host $Message -ForegroundColor Red
    if (-not $NoLaunch) {
        try {
            Add-Type -AssemblyName System.Windows.Forms -ErrorAction Stop
            [void][System.Windows.Forms.MessageBox]::Show(
                $Message,
                "Markdown Editor",
                [System.Windows.Forms.MessageBoxButtons]::OK,
                [System.Windows.Forms.MessageBoxIcon]::Error)
        } catch {}
    }
    exit 1
}

function Get-LaunchCommand {
    $ps1 = Join-Path $Root "markdown-editor.ps1"
    return "powershell -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$ps1`" `"%1`""
}

function Write-RegFiles {
    $cmd = Get-LaunchCommand
    $regValue = ($cmd -replace '\\', '\\') -replace '"', '\"'
    $install = @"
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Classes\SystemFileAssociations\.md\shell\MarkdownEditor]
@="Open with Markdown Editor"
"Icon"="imageres.dll,-102"

[HKEY_CURRENT_USER\Software\Classes\SystemFileAssociations\.md\shell\MarkdownEditor\command]
@="$regValue"
"@
    $uninstall = @"
Windows Registry Editor Version 5.00

[-HKEY_CURRENT_USER\Software\Classes\SystemFileAssociations\.md\shell\MarkdownEditor]
"@
    $ascii = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText((Join-Path $Root "markdown-editor.reg"), $install.Trim() + "`r`n", $ascii)
    [System.IO.File]::WriteAllText((Join-Path $Root "markdown-editor-uninstall.reg"), $uninstall.Trim() + "`r`n", $ascii)
}

function Install-ContextMenu {
    if (-not (Test-Path -LiteralPath $HtmlFile)) {
        Fail "markdown-editor.html is missing at $HtmlFile. Run: node build.js"
    }
    $cmd = Get-LaunchCommand
    New-Item -Path $RegKey -Force | Out-Null
    Set-ItemProperty -Path $RegKey -Name "(default)" -Value "Open with Markdown Editor"
    Set-ItemProperty -Path $RegKey -Name "Icon" -Value "imageres.dll,-102"
    New-Item -Path "$RegKey\command" -Force | Out-Null
    Set-ItemProperty -Path "$RegKey\command" -Name "(default)" -Value $cmd
    Write-RegFiles
    Write-Host "Installed 'Open with Markdown Editor' for .md files (does not change the default opener)."
}

function Uninstall-ContextMenu {
    Remove-Item -Path $RegKey -Recurse -Force -ErrorAction SilentlyContinue
    Write-Host "Removed 'Open with Markdown Editor' from .md files."
}

function Clear-OldLaunchCopies {
    Get-ChildItem -LiteralPath $env:TEMP -Filter "markdown-editor-launch-*.html" -ErrorAction SilentlyContinue |
        Where-Object { $_.LastWriteTime -lt (Get-Date).AddHours(-1) } |
        Remove-Item -Force -ErrorAction SilentlyContinue
}

function Open-Blank {
    if (-not (Test-Path -LiteralPath $HtmlFile)) {
        Fail "markdown-editor.html is missing at $HtmlFile. Run: node build.js"
    }
    if ($NoLaunch) {
        Write-Output $HtmlFile
        return
    }
    Start-Process $HtmlFile
}

function Open-WithFile([string]$mdFile) {
    if (-not (Test-Path -LiteralPath $HtmlFile)) {
        Fail "markdown-editor.html is missing at $HtmlFile. Run: node build.js"
    }
    if (-not (Test-Path -LiteralPath $mdFile)) {
        Fail "File not found: $mdFile"
    }
    $item = Get-Item -LiteralPath $mdFile
    if ($item.PSIsContainer) {
        Fail "Not a file: $mdFile"
    }
    $resolved = $item.FullName
    $ext = [System.IO.Path]::GetExtension($resolved).ToLowerInvariant()
    if (@(".md", ".markdown", ".txt") -notcontains $ext) {
        Fail "Unsupported file type '$ext'. Use .md, .markdown, or .txt."
    }
    Clear-OldLaunchCopies
    $mdName = [System.IO.Path]::GetFileName($resolved)
    $b64 = [Convert]::ToBase64String([System.IO.File]::ReadAllBytes($resolved))
    $html = [System.IO.File]::ReadAllText($HtmlFile, [System.Text.Encoding]::UTF8)
    $idx = $html.IndexOf('</head>')
    if ($idx -lt 0) { Fail "markdown-editor.html has no </head> tag; refusing to inject a payload." }
    $payload = @{ b64 = $b64; filename = $mdName } | ConvertTo-Json -Compress
    $inject = "<script>window.MD_PAYLOAD=$payload;</script>"
    $html = $html.Substring(0, $idx) + $inject + $html.Substring($idx)
    $tmpHtml = Join-Path $env:TEMP ("markdown-editor-launch-{0}.html" -f [guid]::NewGuid().ToString("n"))
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($tmpHtml, $html, $utf8)
    if ($NoLaunch) {
        Write-Output $tmpHtml
        return
    }
    Start-Process $tmpHtml
}

try {
    if ($Install) { Install-ContextMenu; exit 0 }
    if ($Uninstall) { Uninstall-ContextMenu; exit 0 }

    if (-not $Path) {
        Open-Blank
    } else {
        Open-WithFile $Path
    }
} catch {
    Fail $_.Exception.Message
}
