# Markdown Editor launcher
# Opens markdown-editor.html, optionally injecting a .md file as window.MD_PAYLOAD.
# Edit this file. Do not edit markdown-editor.html (generated by build.js).

[CmdletBinding()]
param(
    [Parameter(Position = 0)]
    [string]$Path,
    [switch]$Install,
    [switch]$Uninstall
)

$ErrorActionPreference = "Stop"
$Root = $PSScriptRoot
$HtmlFile = Join-Path $Root "markdown-editor.html"
$RegKey = "HKCU:\Software\Classes\SystemFileAssociations\.md\shell\MarkdownEditor"

function Write-RegFiles {
    $ps1Esc = ($Root + "\markdown-editor.ps1") -replace "\\", "\\"
    $install = @"
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Classes\SystemFileAssociations\.md\shell\MarkdownEditor]
@="Open with Markdown Editor"

[HKEY_CURRENT_USER\Software\Classes\SystemFileAssociations\.md\shell\MarkdownEditor\command]
@="powershell -NoProfile -ExecutionPolicy Bypass -File `"$ps1Esc`" `"%1`""
"@
    $uninstall = @"
Windows Registry Editor Version 5.00

[-HKEY_CURRENT_USER\Software\Classes\SystemFileAssociations\.md\shell\MarkdownEditor]
"@
    [System.IO.File]::WriteAllText((Join-Path $Root "markdown-editor.reg"), $install.TrimStart() + "`r`n", [System.Text.UTF8Encoding]::new($false))
    [System.IO.File]::WriteAllText((Join-Path $Root "markdown-editor-uninstall.reg"), $uninstall.TrimStart() + "`r`n", [System.Text.UTF8Encoding]::new($false))
}

function Install-ContextMenu {
    $ps1 = Join-Path $Root "markdown-editor.ps1"
    $cmd = "powershell -NoProfile -ExecutionPolicy Bypass -File `"$ps1`" `"%1`""
    New-Item -Path $RegKey -Force | Out-Null
    Set-ItemProperty -Path $RegKey -Name "(default)" -Value "Open with Markdown Editor"
    New-Item -Path "$RegKey\command" -Force | Out-Null
    Set-ItemProperty -Path "$RegKey\command" -Name "(default)" -Value $cmd
    Write-RegFiles
    Write-Host "Installed 'Open with Markdown Editor' for .md files (does not change the default opener)."
}

function Uninstall-ContextMenu {
    Remove-Item -Path $RegKey -Recurse -Force -ErrorAction SilentlyContinue
    Write-Host "Removed 'Open with Markdown Editor' from .md files."
}

function Open-Blank {
    if (-not (Test-Path -LiteralPath $HtmlFile)) {
        throw "markdown-editor.html is missing at $HtmlFile. Run: node build.js"
    }
    Start-Process $HtmlFile
}

function Open-WithFile([string]$mdFile) {
    if (-not (Test-Path -LiteralPath $HtmlFile)) {
        throw "markdown-editor.html is missing at $HtmlFile. Run: node build.js"
    }
    $resolved = (Resolve-Path -LiteralPath $mdFile).Path
    if (-not (Test-Path -LiteralPath $resolved)) {
        throw "File not found: $mdFile"
    }
    $mdName = [System.IO.Path]::GetFileName($resolved)
    $b64 = [Convert]::ToBase64String([System.IO.File]::ReadAllBytes($resolved))
    $html = [System.IO.File]::ReadAllText($HtmlFile, [System.Text.Encoding]::UTF8)
    $idx = $html.IndexOf("</head>")
    if ($idx -lt 0) { throw "markdown-editor.html has no </head> — refusing to inject a payload." }
    $payload = @{ b64 = $b64; filename = $mdName } | ConvertTo-Json -Compress
    $inject = "<script>window.MD_PAYLOAD=$payload;</script>"
    $html = $html.Substring(0, $idx) + $inject + $html.Substring($idx)
    $tmpHtml = Join-Path $env:TEMP ("markdown-editor-launch-{0}.html" -f $PID)
    $utf8 = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($tmpHtml, $html, $utf8)
    Start-Process $tmpHtml
}

if ($Install) { Install-ContextMenu; exit 0 }
if ($Uninstall) { Uninstall-ContextMenu; exit 0 }

if (-not $Path) {
    Open-Blank
} else {
    Open-WithFile $Path
}
